# HTML report generator

html_report() {
  local name="$1" file_desc="$2" size_bytes="$3" unit_scheme="$4" lc="$5" owner_group="$6" perms_sym="$7" perms_oct="$8" created_at="$9" modified_at="${10}" rel_path="${11}" abs_path="${12}" gk_assess="${13}" cs_status="${14}" cs_team="${15}" nota_stapled="${16}" verdict="${17}" qstr="${18}" froms="${19}" about_str="${20}"
  local title="finfo: ${name}"
  echo "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>${title}</title><style>body{font-family:ui-monospace,Menlo,Consolas,monospace;background:#111;color:#ddd;padding:16px} h1,h2{color:#9cf} .dim{color:#888} .sec{margin-top:1em} code{color:#cdf}</style></head><body>"
  printf "<h1>%s</h1>\n" "$name"
  echo "<div class=\"sec\"><h2>Essentials</h2>"
  printf "<div>Type: <code>%s</code></div>\n" "$file_desc"
  printf "<div>Size: <code>%s</code> <span class=\"dim\">(%s B)</span></div>\n" "$(_hr_size_fmt ${size_bytes:-0} "$unit_scheme")" "${size_bytes:-0}"
  [[ -n "$lc" ]] && printf "<div>Lines: <code>%s</code></div>\n" "$lc"
  printf "<div>Owner: <code>%s</code> Perms: <code>%s</code> (<span class=\"dim\">%s</span>)</div>\n" "$owner_group" "$perms_sym" "$perms_oct"
  [[ -n "$about_str" ]] && printf "<div>About: <code>%s</code></div>\n" "$about_str"
  echo "</div>"
  echo "<div class=\"sec\"><h2>Timeline</h2>"
  printf "<div>Created: <code>%s</code></div>\n" "$created_at"
  printf "<div>Modified: <code>%s</code></div>\n" "$modified_at"
  echo "</div>"
  echo "<div class=\"sec\"><h2>Paths</h2>"
  printf "<div>Rel: <code>%s</code></div>\n" "$rel_path"
  printf "<div>Abs: <code>%s</code></div>\n" "$abs_path"
  echo "</div>"
  echo "<div class=\"sec\"><h2>Security</h2>"
  printf "<div>Gatekeeper: <code>%s</code> Codesign: <code>%s</code> Team: <code>%s</code> Notarization: <code>%s</code> Verdict: <code>%s</code></div>\n" "$gk_assess" "$cs_status" "$cs_team" "$nota_stapled" "$verdict"
  [[ -n "$qstr" ]] && printf "<div>Quarantine: <code>yes</code> (<span class=\"dim\">%s</span>)</div>\n" "${qstr%%;*}"
  [[ -n "$froms" ]] && printf "<div>WhereFroms: <code>%s</code></div>\n" "$froms"
  echo "</div>"
  echo "</body></html>"
}